### ISSUE TITLE
Adding HTTPS

### ISSUE THREAD

**Issue by konklone** [mmachenry/how-much-snow#13]
It's a tiny, fun site, I know, and I love it -- but it is sending latitude and longitude information across the open internet.

https://sslmate.com has a really nice command line interface, and I'll even donate the $16 for the first year if that makes the difference. =)

**Comment by mmachenry** [comment]
We're getting back into this project. Sorry for the extraordinarily long delay. It's been moved to a real web host and is now properly encrypted with a certificate. Thanks for your issue report.
